config/routes.rb
FrStream::Application.routes.draw do

  root 'movies#index'

  get "home/index"
  get "home/show"

  get 'movies/progress_poll', to: "movies#progress_poll"
  get 'movies/update_movies', to: "movies#update_movies"
  resources :movies, only: [:index, :show]  do
    member do
      get :convert_to_mp4
    end
  end

  

end

app/models/movie.rb
class Movie
  
  include Mongoid::Document
  
  field :title, type: String
  field :url, type: String
  field :duration, type: String
  field :path, type: String
  field :type, type: String
  field :converted, type: Boolean, default: false


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@movies = Dir.glob("public/movies/**.mp4").map{|l| l.sub("public/", "")}
    @movies = Movie.all
    #binding.pry
  end
  def show
    #binding.pry
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
    @avi_movies = Movie.where(type: "avi")
    @mp4_movies = Movie.where(type: "mp4")
    #binding.pry
  end

  def show
    @movie = Movie.find params[:id]
  end

  def convert_to_mp4
    @movie = Movie.find params[:id]
    Resque.enqueue(Converter, @movie.path)
    @movie.converted = true
    @movie.save
    redirect_to movies_path, flash: {notice: "your job has been queued successfully"}
  end

  def progress_poll
    MovieParser.update_movies
    @mp4_movies = Movie.where(type: "mp4")
    @txts_paths = @mp4_movies.map{|l| l.path.concat('.txt')}
    @progress = {}
    @txts_paths.each do |movie|
      f = File.open(movie)
      f.seek(-58, IO::SEEK_END)
      movie_id = Movie.find_by(title: movie.sub("#{Rails.configuration.streamable_movies_path + 'mp4/'}","").sub(".mp4.txt",".avi")).id.to_s
      @progress[movie_id] = f.readline[5..15]
      avi_movie_duration = Movie.find_by(title: movie.sub("#{Rails.configuration.streamable_movies_path + 'mp4/'}","").sub(".mp4.txt",".avi")).duration
      avi_movie_duration_in_seconds = ffmpeg_time_to_second avi_movie_duration
      mp4_movie_duration_in_seconds = ffmpeg_time_to_second @progress[movie_id]
      progress_rate = (mp4_movie_duration_in_seconds * 100) / avi_movie_duration_in_seconds
      @progress[movie_id] = progress_rate
    end
    #binding.pry
    #render json: @progress.to_json
  end

  def update_movies
    MovieParser.update_movies
    redirect_to movies_path
  end

  def ffmpeg_time_to_second timestamp
    hours = timestamp[0..1].to_i * 60 * 60
    minutes = timestamp[3..4].to_i * 60
    seconds = timestamp[6..7].to_i
    @duration_in_second = hours + minutes + seconds
  end

  #def get_movie_duration movie
  #  input = "/Users/molz/Desktop/films/avi/Bad Country 2014 FRENCH DVDRiP XviD-CARPEDIEM.avi"
  #  cmd = "ffmpeg -i '#{input}' 2>&1 | grep 'Duration'| cut -d ' ' -f 4 | sed s/,//"
  #  @movie_duration = %x(#{cmd}).sub("\n","")
  #end

  #tail -r Bad\ Country\ 2014\ FRENCH\ DVDRiP\ XviD-CARPEDIEM.mp4.txt | grep -m 1 '.'|cut -d' ' -f12

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/home/index.html.haml
%ul
  - @movies.each do |movie|
    %li
      %label
        = movie
      = link_to "lien", "#"
      =# binding.pry

app/views/home/show.html.haml
-#%video#film{controls: true, style:"position: absolute; top: 0; left: 0; width: 100%; height: 100%;"}
-#  %source{src: "/film.mp4"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FrStream
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %flash_messages
      - unless flash == {}
        = flash[:error]
        = flash[:notice]
    = yield

app/views/movies/index.html.haml
%section.container
  %article.avi
    %div
      %h3 Streamer
      = link_to "Update Movies", movies_update_movies_path, class: "btn btn-large btn-info"
    %h3
      avi Movies (to be converted)
    %ul
      - @avi_movies.each do |movie|
        %li
          %span
            = movie.title
            - if movie.converted == false
              = link_to "Convert to mp4", convert_to_mp4_movie_path(movie), class: 'btn btn-small btn-info'
            - else
              %div.progress
                %div.progress-bar{role: "progressbar", style: "width:0%;", class: movie.id}
              %button#click
                Refresh
  %article.mp4
    %h3
      mp4 Movies (streamable)
    %ul
      - @mp4_movies.each do |movie|
        %li
          %span
            = link_to movie.title, movie_path(movie)
:coffee
  $ ->
    ( poll = ->
      setTimeout ( ->
        $.get( "#{ movies_progress_poll_url }", (data) ->
          console.log(data)
        )
        poll()
      ), 2500
    )()

app/views/movies/progress_poll.js.erb
<%- @progress.each do |key, value| %>
  $(".<%= key %>.progress-bar").css({"width":"<%= value %>%"});
<% end %>

app/views/movies/show.html.haml
%video#film{controls: true, style:"position: absolute; top: 0; left: 0; width: 100%; height: 100%;"}
  %source{src: "/movies/mp4/" + @movie.title}

:sass
  body
    background-color: black